{
    "projects": {
        "admin_hamsafar": {
            "schemaPath": "src/schema.graphql",
            "includes": ["**/*.graphql"],
            "extensions": {
                "endpoints": {
                    "default": "http://limoonline/graphql/"
                }
            }
        }
    }
}